Repository bastionzero/bzero, pull requests merged in 2022-08, with the labels that each got.

#77 Update Go version to 1.18.5
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  VERSION
Labels: dependencies

#120 Daemon shutdown improvements
  VERSION
  bctl/agent/agent.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/plugin/db/actions/dial/dial.go
  bctl/daemon/plugin/db/db.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bctl/daemon/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/plugin/kube/actions/restapi/restapi.go
  bctl/daemon/plugin/kube/actions/stream/stream.go
  bctl/daemon/plugin/kube/kube.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/plugin/shell/shell.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/daemon/plugin/ssh/ssh.go
  bctl/daemon/plugin/web/actions/webdial/webdial.go
  bctl/daemon/plugin/web/actions/webwebsocket/webwebsocket.go
  bctl/daemon/plugin/web/web.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/bzos/errors.go
  bzerolib/bzos/shutdown.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/keysplitting/bzcert/bzcertverifier.go
  bzerolib/keysplitting/bzcert/errors.go
  bzerolib/plugin/shell/errors.go
Labels: enhancement

#124 Fix: mark shell as connected on first stream message
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell.go
Labels: bug

#121 Websocket Refactor Part I: Split out SignalR and Websocket Code
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/datachannel/datachannel.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/bzhttp/bzhttp.go
  bzerolib/channels/websocket/challenge/challenge.go
  bzerolib/channels/websocket/channel.go
  bzerolib/channels/websocket/signalr.go
  bzerolib/channels/websocket/targetselect.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/channels/websocket/websocketmessages.go
  bzerolib/connection/broker/broker.go
  bzerolib/connection/httpclient/httpclient.go
  bzerolib/connection/messenger/signalr/invocation.go
  bzerolib/connection/messenger/signalr/messages.go
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/transporter/websocket/websocket.go
  bzerolib/controllers/agentcontroller/agentcontroller.go
  bzerolib/controllers/agentcontroller/messages.go
  bzerolib/controllers/connectionnodecontroller/connectionnodecontroller.go
  bzerolib/controllers/connectionnodecontroller/messages.go
  bzerolib/controllers/spacescontroller/messages.go
  bzerolib/controllers/spacescontroller/spacescontroller.go
  bzerolib/go.mod
Labels: refactor

#122 Websocket Refactor Part 1: Part 2: Tests!
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/keysplitting/keysplitting.go
  bzerolib/connection/httpclient/httpclient_test.go
  bzerolib/connection/messenger/signalr/mocks.go
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/messenger/signalr/signalr_test.go
  bzerolib/connection/transporter/websocket/mocks.go
  bzerolib/connection/transporter/websocket/websocket_test.go
  bzerolib/tests/mocks/mockserver.go
Labels: testing

#127 Release 08/17/2022
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/daemon/config.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/keysplitting/bzcert/bzcert.go
  bctl/daemon/keysplitting/bzcert/mocks.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/plugin/db/actions/dial/dial.go
  bctl/daemon/plugin/db/db.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bctl/daemon/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/plugin/kube/actions/restapi/restapi.go
  bctl/daemon/plugin/kube/actions/stream/stream.go
  bctl/daemon/plugin/kube/kube.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/plugin/shell/shell.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/daemon/plugin/ssh/ssh.go
  bctl/daemon/plugin/web/actions/webdial/webdial.go
  bctl/daemon/plugin/web/actions/webwebsocket/webwebsocket.go
  bctl/daemon/plugin/web/web.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/bzos/errors.go
  bzerolib/bzos/shutdown.go
  bzerolib/channels/websocket/signalr.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/channels/websocket/websocketmessages.go
  bzerolib/go.sum
  bzerolib/keysplitting/bzcert/bzcert.go
  bzerolib/keysplitting/bzcert/bzcertverifier.go
  bzerolib/keysplitting/bzcert/errors.go
  bzerolib/keysplitting/bzcert/mocks.go
  bzerolib/keysplitting/bzcert/zliconfig/zliconfig.go
  bzerolib/plugin/shell/errors.go
Labels: release

#130 Fix race condition during concurrent SSH connections
  VERSION
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/daemon/plugin/ssh/ssh.go
  bzerolib/plugin/ssh/generatekeys.go
  bzerolib/plugin/ssh/identityfile.go
Labels: bug

#132 Release 08/25
  VERSION
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/daemon/plugin/ssh/ssh.go
  bzerolib/plugin/ssh/generatekeys.go
  bzerolib/plugin/ssh/identityfile.go
Labels: release

#128 Agent recovery part 1: healthcheck pongs
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/vault/vault.go
  bctl/daemon/daemon.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/report/errorreport.go
  bzerolib/report/restartreport.go
  bzerolib/tests/hardmode.go
  start-dev.sh
Labels: enhancement

#136 Modify system test codebuild spec to clone infra branch based on env var
  Codebuild/system-test-codebuild.yaml
  VERSION
Labels: enhancement
