Repository bastionzero/bzero, pull requests merged in 2022-12, with the labels that each got.

#171 Move .mod files to go1.18
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  DockerFile
  README.md
  VERSION
  bctl/agent/config/client/systemd.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/registration/registration.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/connection/httpclient/httpclient.go
  bzerolib/connection/httpclient/httpclient_test.go
  bzerolib/go.mod
  bzerolib/go.sum
Labels: dependencies

#193 Hotfix: Exit if user attempt to register when agent is already registered
  VERSION
  bctl/agent/config/data/mocks.go
  bctl/agent/main.go
Labels: bug, Hotfix

#195 apply registration hotfix
  VERSION
  bctl/agent/config/data/mocks.go
  bctl/agent/main.go
Labels: bug

#189 Feat/onelogin integration
  .github/workflows/systemtest-ci-develop.yml
  .github/workflows/systemtest-ci-master.yml
  VERSION
  bctl/agent/config/data/data.go
  bzerolib/mrtap/bzcert/bzcertverifier.go
  bzerolib/mrtap/bzcert/bzcertverifier_test.go
  bzerolib/mrtap/bzcert/errors.go
  bzerolib/mrtap/util/util.go
Labels: Feature Branch, ci-run-onelogin, ci-run-google

#199 Version bump
  VERSION
Labels: bug, Hotfix

#200 Arm64 apt cgo hotfix
  VERSION
Labels: bug, Hotfix
