Repository bastionzero/bzero, pull requests merged in 2022-07, with the labels that each got.

#111 Refactor: ssh formatting / organization
  VERSION
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bzerolib/plugin/ssh/generatekeys.go
Labels: refactor

#107 Discard Initial TCP Connection
  VERSION
  bctl/daemon/plugin/db/actions/dial/dial.go
  bctl/daemon/servers/dbserver/dbserver.go
Labels: bug

#113 Fix broken sudo access for bzero's managed users
  VERSION
  bzerolib/unix/sudoers/sudoers.go
  bzerolib/unix/unixuser/unixuser_test.go
  bzerolib/unix/unixuser/useradd.go
Labels: bug

#114 Add support for known_hosts
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/agent/plugin/ssh/ssh.go
  bctl/daemon/daemon.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/daemon/plugin/ssh/ssh.go
  bctl/daemon/servers/sshserver/sshserver.go
  bzerolib/plugin/ssh/generatekeys.go
  bzerolib/plugin/ssh/identityfile.go
  bzerolib/plugin/ssh/knownhosts.go
Labels: Feature Branch

#101 [Feat: FUD] Support file transfer via transparent scp
  VERSION
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/agent/plugin/ssh/ssh.go
  bctl/daemon/daemon.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/daemon/plugin/ssh/ssh.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/bzio/mocks.go
  bzerolib/bzio/stdio.go
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/plugin/ssh/generatekeys.go
  bzerolib/plugin/ssh/identityfile.go
  bzerolib/plugin/ssh/knownhosts.go
  bzerolib/plugin/ssh/ssh.go
Labels: Feature Branch

#115 Address data truncation and out-of-order messages
  VERSION
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/plugin/db/actions/dial/dial.go
  bctl/daemon/servers/dbserver/dbserver.go
Labels: bug

#117 Fixes a bug where kube exec fails for commands that do not pass stdin to container
  VERSION
  bctl/agent/plugin/kube/actions/exec/exec.go
  bctl/agent/plugin/kube/actions/exec/exec_test.go
  bctl/agent/plugin/kube/actions/exec/mocks.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bzerolib/plugin/kube/actions/exec/execpayloads.go
Labels: bug

#118 Release 07/20
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/keysplitting/keysplitting.go
  bctl/agent/plugin/kube/actions/exec/exec.go
  bctl/agent/plugin/kube/actions/exec/exec_test.go
  bctl/agent/plugin/kube/actions/exec/mocks.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
  bctl/agent/plugin/ssh/ssh.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/keysplitting/errors.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/plugin/db/actions/dial/dial.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/daemon/plugin/ssh/ssh.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/bzio/mocks.go
  bzerolib/bzio/stdio.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/keysplitting/bzcert/bzcert.go
  bzerolib/keysplitting/bzcert/bzcertverifier.go
  bzerolib/keysplitting/bzcert/mocks.go
  bzerolib/keysplitting/bzcert/zliconfig/zliconfig.go
  bzerolib/keysplitting/util/util.go
  bzerolib/logger/logger.go
  bzerolib/logger/mocks.go
  bzerolib/plugin/kube/actions/exec/execpayloads.go
  bzerolib/plugin/ssh/generatekeys.go
  bzerolib/plugin/ssh/identityfile.go
  bzerolib/plugin/ssh/knownhosts.go
  bzerolib/plugin/ssh/ssh.go
  bzerolib/tests/keypair.go
  bzerolib/unix/sudoers/sudoers.go
  bzerolib/unix/unixuser/unixuser_test.go
  bzerolib/unix/unixuser/useradd.go
Labels: release

#119 Pass runtime config to the daemon via environment variables instead of flags
  VERSION
  bctl/daemon/config.go
  bctl/daemon/daemon.go
Labels: enhancement

#109 Validate BZCert in Daemon and bubble up errors
  VERSION
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exitcodes/exitcodes.go
  bctl/daemon/keysplitting/bzcert/bzcert.go
  bctl/daemon/keysplitting/bzcert/mocks.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/keysplitting/bzcert/bzcert.go
  bzerolib/keysplitting/bzcert/bzcertverifier.go
  bzerolib/keysplitting/bzcert/errors.go
  bzerolib/keysplitting/bzcert/mocks.go
  bzerolib/keysplitting/bzcert/zliconfig/zliconfig.go
Labels: enhancement

#112 Fix race condition in new data channel flow
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/daemon/daemon.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/channels/websocket/signalr.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/channels/websocket/websocketmessages.go
Labels: bug
