Repository bastionzero/bzero, pull requests merged in 2022-05, with the labels that each got.

#67 Unit tests for kube actions
  README.md
  VERSION
  bctl/agent/plugin/kube/actions/exec/exec.go
  bctl/agent/plugin/kube/actions/exec/exec_test.go
  bctl/agent/plugin/kube/actions/exec/mocks.go
  bctl/agent/plugin/kube/actions/portforward/portforward_test.go
  bctl/agent/plugin/kube/actions/portforward/portforwardaction.go
  bctl/agent/plugin/kube/actions/restapi/restapi.go
  bctl/agent/plugin/kube/actions/restapi/restapi_test.go
  bctl/agent/plugin/kube/actions/stream/stream.go
  bctl/agent/plugin/kube/actions/stream/stream_test.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_test.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bctl/daemon/plugin/kube/actions/exec/exec_test.go
  bctl/daemon/plugin/kube/actions/exec/spdy.go
  bctl/daemon/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/plugin/kube/actions/portforward/portforward_test.go
  bctl/daemon/plugin/kube/actions/portforward/utils.go
  bctl/daemon/plugin/kube/actions/restapi/restapi.go
  bctl/daemon/plugin/kube/actions/restapi/restapi_test.go
  bctl/daemon/plugin/kube/actions/stream/stream_test.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/logger/mock/mocklogger.go
  bzerolib/logger/mocks.go
  bzerolib/plugin/kube/actions/restapi/restapi.go
  bzerolib/plugin/kube/utils/spdyconstants.go
  bzerolib/tests/assertions.go
  bzerolib/tests/mocks.go
  img/test-coverage.png
  run-tests.sh
Labels: testing

#76 Schema version handshake
  bctl/agent/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting.go
  bzerolib/keysplitting/message/dataackpayload.go
  bzerolib/keysplitting/message/datapayload.go
  bzerolib/keysplitting/message/keysplittingmessage.go
  bzerolib/keysplitting/message/synackpayload.go
  bzerolib/keysplitting/message/synpayload.go
Labels: bug

#79 Fix/bamboo login
  VERSION
  bctl/daemon/plugin/web/actions/webdial/webdial.go
Labels: bug

#82 Fix codebuild spec to not include environment variables that are now included in system test CB job
  Codebuild/system-test-codebuild.yaml
  VERSION
Labels: testing

#78 Use npm@8 when running system tests
  Codebuild/system-test-codebuild.yaml
  VERSION
Labels: enhancement

#86 Release 05/17
  Codebuild/system-test-codebuild.yaml
  VERSION
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
  bzerolib/channels/websocket/websocket.go
Labels: release

#89 Fix Kube Stream Action Not Dying
  VERSION
  bctl/agent/plugin/kube/actions/stream/stream.go
Labels: bug

#91 increase timeout to 1 minute
  VERSION
  bctl/daemon/datachannel/datachannel.go
Labels: bug

#93 Release 05 27
  VERSION
  bctl/agent/plugin/kube/actions/stream/stream.go
  bctl/daemon/datachannel/datachannel.go
Labels: release
