Repository bastionzero/bzero, pull requests merged in 2022-04, with the labels that each got.

#59 Fix API call params following session token changes
  VERSION
  bctl/daemon/daemon.go
Labels: bug, enhancement

#62 Fix Kube Port Forward
  VERSION
  bctl/agent/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bzerolib/stream/message/stream.go
Labels: bug

#56 CWC-1642: Update Stream Messages and move files to bzerolib
  VERSION
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/db/actions/dial/dial.go
  bctl/agent/plugin/db/db.go
  bctl/agent/plugin/kube/actions/exec/exec.go
  bctl/agent/plugin/kube/actions/exec/terminalsizequeue.go
  bctl/agent/plugin/kube/actions/portforward/portforward.go
  bctl/agent/plugin/kube/actions/portforward/portforwardaction.go
  bctl/agent/plugin/kube/actions/portforward/portforwardrequest.go
  bctl/agent/plugin/kube/actions/restapi/restapi.go
  bctl/agent/plugin/kube/actions/stream/stream.go
  bctl/agent/plugin/kube/actions/stream/streampayload.go
  bctl/agent/plugin/kube/kube.go
  bctl/agent/plugin/web/actions/webdial/webdial.go
  bctl/agent/plugin/web/actions/webwebsocket/webwebsocket.go
  bctl/agent/plugin/web/actions/webwebsocket/webwebsocketpayloads.go
  bctl/daemon/plugin/db/actions/dial/dial.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bctl/daemon/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/plugin/kube/actions/restapi/restapi.go
  bctl/daemon/plugin/kube/actions/stream/stream.go
  bctl/daemon/plugin/web/actions/webdial/webdial.go
  bctl/daemon/plugin/web/actions/webwebsocket/webwebsocket.go
  bzerolib/plugin/db/actions/dial/dial.go
  bzerolib/plugin/kube/actions/exec/exec.go
  bzerolib/plugin/kube/actions/exec/execpayloads.go
  bzerolib/plugin/kube/actions/portforward/portforward.go
  bzerolib/plugin/kube/actions/portforward/portforwardpayload.go
  bzerolib/plugin/kube/actions/restapi/restapi.go
  bzerolib/plugin/kube/actions/restapi/restapipayloads.go
  bzerolib/plugin/kube/actions/stream/stream.go
  bzerolib/plugin/kube/actions/stream/streampayload.go
  bzerolib/plugin/web/actions/webdial/webdial.go
  bzerolib/plugin/web/actions/webwebsocket/webwebsocketpayloads.go
  bzerolib/stream/message/stream.go
  bzerolib/stream/stdreader/stdreader.go
  bzerolib/stream/stdwriter/stdwriter.go
Labels: enhancement

#55 Feat/shell
  .github/workflows/ci.yaml
  README.md
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_test.go
  bctl/agent/plugin/shell/shell.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/plugin/shell/shell.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/webserver/webserver.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/channels/websocket/signalr.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/controllers/connectionnodecontroller/connectionnodecontroller.go
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/keysplitting/message/keysplittingmessage.go
  bzerolib/logger/logger.go
  bzerolib/logger/mock/mocklogger.go
  bzerolib/plugin/plugin.go
  bzerolib/plugin/shell/shell.go
  bzerolib/ringbuffer/ringbuffer.go
  bzerolib/ringbuffer/ringbuffer_test.go
  bzerolib/stream/message/stream.go
Labels: Feature Branch

#51 Add system tests
  .github/pull_request_template.md
  .github/workflows/ci.yaml
  .github/workflows/codebuild-check-pr.yml
  .github/workflows/codebuild-unit-test.yml
  .github/workflows/systemtest-ci-develop.yml
  .gitignore
  Codebuild/check-pr.yml
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  DockerFile
  VERSION
Labels: enhancement

#71 Ensure local TCP connection write is non-blocking
  .github/workflows/systemtest-ci-develop.yml
  bctl/daemon/plugin/db/actions/dial/dial.go
Labels: bug

#72 One action per kube
  VERSION
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/db/db.go
  bctl/agent/plugin/kube/actions/exec/exec.go
  bctl/agent/plugin/kube/actions/exec/stdreader.go
  bctl/agent/plugin/kube/actions/exec/stdwriter.go
  bctl/agent/plugin/kube/actions/portforward/portforwardaction.go
  bctl/agent/plugin/kube/actions/portforward/portforwardrequest.go
  bctl/agent/plugin/kube/actions/restapi/restapi.go
  bctl/agent/plugin/kube/actions/stream/stream.go
  bctl/agent/plugin/kube/kube.go
  bctl/agent/plugin/web/web.go
  bctl/agent/registration/registration.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bctl/daemon/plugin/kube/actions/exec/spdy.go
  bctl/daemon/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/plugin/kube/actions/portforward/utils.go
  bctl/daemon/plugin/kube/actions/restapi/restapi.go
  bctl/daemon/plugin/kube/actions/stream/stream.go
  bctl/daemon/plugin/kube/kube.go
  bctl/daemon/plugin/kube/utils/spdy.go
  bctl/daemon/plugin/kube/utils/utils.go
  bctl/daemon/plugin/web/actions/webdial/webdial.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bzerolib/bzhttp/bzhttp.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/controllers/connectionnodecontroller/connectionnodecontroller.go
  bzerolib/controllers/spacescontroller/spacescontroller.go
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/plugin/kube/utils/spdyconstants.go
  bzerolib/plugin/kube/utils/utils.go
Labels: enhancement

#73 Fix system test yml to include iperf
  Codebuild/system-test-codebuild.yaml
  VERSION
Labels: testing
