Repository bastionzero/bzero, pull requests merged in 2022-10, with the labels that each got.

#155 add debugf output to daemon kube server
  VERSION
  bctl/daemon/servers/kubeserver/kubeserver.go
Labels: bug

#157 Release/10 06
  VERSION
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlconnection/connection_integration_test.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/keysplitting/bzcert/bzcert.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_integration_test.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/transporter/websocket/websocket.go
  bzerolib/tests/errors.go
Labels: release

#158 Log port being used in kubeserver
  VERSION
  bctl/daemon/servers/kubeserver/kubeserver.go
Labels: Hotfix, logging

#139 Clean up readme
  CONTRIBUTING.md
  LICENSE
  README.md
  VERSION
  run-tests.sh
Labels: documentation

#160 Log port being used in kubeserver (hotfix #158)
  VERSION
  bctl/daemon/servers/kubeserver/kubeserver.go
Labels: logging

#147 CWC-1940: Fix replay attack
  VERSION
  bctl/agent/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bzerolib/keysplitting/message/keysplittingmessage.go
Labels: bug, testing

#162 Release 10-13-2022
  CONTRIBUTING.md
  LICENSE
  README.md
  VERSION
  bctl/agent/keysplitting/keysplitting.go
  bctl/agent/plugin/kube/actions/exec/exec.go
  bctl/agent/plugin/kube/actions/exec/exec_test.go
  bctl/agent/plugin/kube/actions/exec/stdreader.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bzerolib/keysplitting/message/keysplittingmessage.go
  run-tests.sh
Labels: release

#167 Cancellable Error and Restart Reports
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/agentidentity/agentidentity.go
  bctl/agent/controlconnection/connection.go
  bctl/daemon/daemon.go
  bzerolib/connection/httpclient/httpclient.go
  bzerolib/connection/httpclient/httpclient_test.go
  bzerolib/report/errorreport.go
  bzerolib/report/restartreport.go
Labels: bug

#168 Refactor Agent Startup
  DockerFile
  VERSION
  bctl/agent/agent.go
  bctl/agent/agent_test.go
  bctl/agent/main.go
  bctl/agent/mocks/config.go
  bctl/agent/mocks/registration.go
  bctl/agent/registration/registration.go
  bctl/agent/vault/vault.go
  bzerolib/logger/logger.go
  start-dev.sh
  update-agent-version.sh
Labels: testing, refactor

#170 Add two errors for the daemon to handle
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bzerolib/plugin/ssh/errors.go
  bzerolib/unix/unixuser/errors.go
  bzerolib/unix/unixuser/unixuser.go
  bzerolib/unix/unixuser/useradd.go
Labels: bug

#153 Send agent logs to S3
  .github/pull_request_template.md
  VERSION
  bctl/agent/agent.go
  bctl/agent/agentreport/logreport.go
  bctl/agent/agentreport/restartreport.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bzerolib/connection/agentmessage/agentmessage.go
Labels: Feature Branch

#169 Agent Config Refactor
  VERSION
  bctl/agent/agent.go
  bctl/agent/config/config.go
  bctl/agent/config/config_test.go
  bctl/agent/config/data.go
  bctl/agent/config/kubernetes.go
  bctl/agent/config/systemd.go
  bctl/agent/controlchannel/agentidentity/agentidentity.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/main.go
  bctl/agent/mocks/config.go
  bctl/agent/registration/registration.go
  bctl/agent/vault/vault.go
  bctl/daemon/daemon.go
  bctl/go.mod
  bzerolib/connection/transporter/websocket/websocket.go
  bzerolib/go.mod
Labels: bug, refactor

#166 Keypair
  VERSION
  bctl/agent/agent.go
  bctl/agent/config/client/kubernetes.go
  bctl/agent/config/client/kubernetes_test.go
  bctl/agent/config/client/systemd.go
  bctl/agent/config/client/systemd_test.go
  bctl/agent/config/config.go
  bctl/agent/config/config_test.go
  bctl/agent/config/data/data.go
  bctl/agent/config/data/data_test.go
  bctl/agent/config/data/mocks.go
  bctl/agent/config/mocks.go
  bctl/agent/controlchannel/agentidentity/agentidentity.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/controlconnection/connection_integration_test.go
  bctl/agent/controlconnection/connection_test.go
  bctl/agent/keysplitting/keysplitting.go
  bctl/agent/keysplitting/mocks.go
  bctl/agent/main.go
  bctl/agent/mocks/agentconfig.go
  bctl/agent/registration/registration.go
  bctl/daemon/daemon.go
  bctl/daemon/keysplitting/bzcert/bzcert.go
  bctl/daemon/keysplitting/bzcert/mocks.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/keypair/keypair.go
  bzerolib/keypair/privatekey.go
  bzerolib/keypair/publickey.go
  bzerolib/keysplitting/bzcert/bzcertverifier.go
  bzerolib/keysplitting/message/keysplittingmessage.go
  bzerolib/messagesigner/messagesigner.go
  bzerolib/messagesigner/mocks.go
  bzerolib/tests/keypair.go
Labels: refactor

#172 Fix bug when SSHing as a nonexistent user
  VERSION
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_test.go
  bctl/agent/plugin/ssh/ssh.go
  bctl/daemon/datachannel/datachannel.go
Labels: bug

#175 Extend daemon's short privatekey
  VERSION
  bctl/daemon/keysplitting/bzcert/bzcert.go
Labels: bug

#161 Rename Keysplitting to MrTAP
  README.md
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/controlconnection/connection_test.go
  bctl/agent/datachannel/datachannel.go
  bctl/agent/mrtap/mocks.go
  bctl/agent/mrtap/mrtap.go
  bctl/agent/plugin/kube/actions/restapi/restapi.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/mrtap/bzcert/bzcert.go
  bctl/daemon/mrtap/bzcert/mocks.go
  bctl/daemon/mrtap/errors.go
  bctl/daemon/mrtap/mrtap.go
  bctl/daemon/mrtap/mrtap_test.go
  bctl/daemon/plugin/db/db.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bctl/daemon/plugin/kube/actions/portforward/portforward.go
  bctl/daemon/plugin/kube/actions/restapi/restapi.go
  bctl/daemon/plugin/kube/actions/restapi/restapi_test.go
  bctl/daemon/plugin/kube/actions/stream/stream.go
  bctl/daemon/plugin/kube/kube.go
  bctl/daemon/plugin/shell/shell.go
  bctl/daemon/plugin/ssh/ssh.go
  bctl/daemon/plugin/web/web.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_test.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/connection/agentmessage/agentmessage.go
  bzerolib/connection/agentmessage/agentmessage_test.go
  bzerolib/error/error.go
  bzerolib/error/error_test.go
  bzerolib/keysplitting/message/keysplittingmessage.go
  bzerolib/mrtap/bzcert/bzcert.go
  bzerolib/mrtap/bzcert/bzcertverifier.go
  bzerolib/mrtap/bzcert/errors.go
  bzerolib/mrtap/bzcert/mocks.go
  bzerolib/mrtap/bzcert/zliconfig/zliconfig.go
  bzerolib/mrtap/message/dataackpayload.go
  bzerolib/mrtap/message/datapayload.go
  bzerolib/mrtap/message/mrtapmessage.go
  bzerolib/mrtap/message/mrtapmessage_test.go
  bzerolib/mrtap/message/synackpayload.go
  bzerolib/mrtap/message/synpayload.go
  bzerolib/mrtap/util/util.go
  bzerolib/plugin/ssh/generatekeys.go
  bzerolib/stream/message/stream.go
Labels: refactor
