Repository bastionzero/bzero, pull requests merged in 2022-06, with the labels that each got.

#97 Release 06/01
  VERSION
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_test.go
  bctl/agent/plugin/ssh/authorizedkeys/mocks.go
  bctl/agent/plugin/ssh/ssh.go
  bctl/daemon/daemon.go
  bctl/daemon/plugin/kube/actions/exec/spdy.go
  bctl/daemon/plugin/kube/kube.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/plugin/ssh/actions/opaquessh/generatekeys.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/ssh.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/bzio/fileio.go
  bzerolib/bzio/mocks.go
  bzerolib/bzio/stdio.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/controllers/connectionnodecontroller/connectionnodecontroller.go
  bzerolib/controllers/connectionnodecontroller/messages.go
  bzerolib/filelock/filelock.go
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/plugin/plugin.go
  bzerolib/plugin/shell/shell.go
  bzerolib/plugin/ssh/ssh.go
  bzerolib/tests/sample_keys.go
  bzerolib/unix/filemode/filemode.go
  bzerolib/unix/unixuser/permissions.go
  bzerolib/unix/unixuser/unixuser.go
Labels: release

#96 Update shell to use unixuser
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/mocks.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_test.go
  bctl/agent/plugin/shell/shell.go
  bzerolib/unix/unixuser/permissions.go
  bzerolib/unix/unixuser/unixuser.go
Labels: bug

#95 Universal Connect
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/logger/logger.go
Labels: Feature Branch

#98 Lazy User Creation
  Codebuild/unit-test.yml
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_test.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_test.go
  bctl/agent/plugin/ssh/ssh.go
  bzerolib/go.mod
  bzerolib/unix/filemode/filemode.go
  bzerolib/unix/unixuser/permissions.go
  bzerolib/unix/unixuser/unixuser.go
  bzerolib/unix/unixuser/unixuser_test.go
  bzerolib/unix/unixuser/useradd.go
Labels: enhancement

#99 Flag lineup
  VERSION
  bctl/agent/agent.go
Labels: enhancement

#100 Release 6/7/22
  Codebuild/unit-test.yml
  VERSION
  bctl/agent/agent.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/mocks.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_test.go
  bctl/agent/plugin/shell/shell.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_test.go
  bctl/agent/plugin/ssh/ssh.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/go.mod
  bzerolib/logger/logger.go
  bzerolib/unix/filemode/filemode.go
  bzerolib/unix/unixuser/permissions.go
  bzerolib/unix/unixuser/unixuser.go
  bzerolib/unix/unixuser/unixuser_test.go
  bzerolib/unix/unixuser/useradd.go
Labels: release

#102 remove vault from tracked files
  VERSION
  packaging/apt/conffiles
Labels: bug, Hotfix

#104 Hotfix to get bzero ssh to work with ssm-agent
  VERSION
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
Labels: Hotfix

#103 Merge Agent SSM to Bzero Transition Hotfixes (#102) (#104)
  VERSION
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys.go
  bzerolib/go.sum
  packaging/apt/conffiles
Labels: Hotfix

#105 Fix the funniness
  VERSION
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/db/actions/dial/dial.go
  bctl/daemon/plugin/db/actions/dial/dial.go
Labels: Hotfix

#106 Hotfixes 6/25
  VERSION
  bctl/agent/plugin/db/actions/dial/dial.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bzerolib/bzhttp/bzhttp.go
  bzerolib/channels/websocket/websocket.go
Labels: Hotfix

#108 Apply 6/25 Hotfixes to develop
  VERSION
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/db/actions/dial/dial.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/daemon/plugin/db/actions/dial/dial.go
  bzerolib/bzhttp/bzhttp.go
  bzerolib/channels/websocket/websocket.go
Labels: bug
