Repository bastionzero/bzero, pull requests merged in 2022-09, with the labels that each got.

#137 Release 09-01-2022
  Codebuild/system-test-codebuild.yaml
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/vault/vault.go
  bctl/daemon/daemon.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/report/errorreport.go
  bzerolib/report/restartreport.go
  bzerolib/tests/hardmode.go
  start-dev.sh
Labels: release

#135 Agent failsafe & recovery part 2: manual restart message
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bctl/agent/datachannel/datachannel.go
  bzerolib/channels/agentmessage/agentmessage.go
  bzerolib/channels/websocket/websocket.go
Labels: Feature Branch

#138 Update agent version vault
  VERSION
  bctl/agent/agent.go
Labels: bug

#140 Don't import ginkgo in a non-test file
  VERSION
  bctl/agent/plugin/kube/actions/exec/exec_test.go
  bctl/agent/plugin/kube/actions/portforward/portforward_test.go
  bctl/agent/plugin/kube/actions/restapi/restapi_test.go
  bctl/agent/plugin/kube/actions/stream/stream_test.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_test.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_test.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/plugin/kube/actions/exec/exec_test.go
  bctl/daemon/plugin/kube/actions/portforward/portforward_test.go
  bctl/daemon/plugin/kube/actions/restapi/restapi_test.go
  bctl/daemon/plugin/kube/actions/stream/stream_test.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bzerolib/logger/mocks.go
Labels: bug

#142 Release 09-08
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/kube/actions/exec/exec_test.go
  bctl/agent/plugin/kube/actions/portforward/portforward_test.go
  bctl/agent/plugin/kube/actions/restapi/restapi_test.go
  bctl/agent/plugin/kube/actions/stream/stream_test.go
  bctl/agent/plugin/shell/actions/defaultshell/defaultshell_test.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_test.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_test.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/daemon/plugin/kube/actions/exec/exec_test.go
  bctl/daemon/plugin/kube/actions/portforward/portforward_test.go
  bctl/daemon/plugin/kube/actions/restapi/restapi_test.go
  bctl/daemon/plugin/kube/actions/stream/stream_test.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bzerolib/channels/agentmessage/agentmessage.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/logger/mocks.go
Labels: release

#143 Use an interactive login shell for the defaultshell action
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
Labels: bug

#141 Add debug flag to daemon
  VERSION
  bctl/daemon/config.go
  bctl/daemon/daemon.go
  bzerolib/logger/logger.go
Labels: enhancement

#145 develop - interactive login shell
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
Labels: bug

#126 Websocket Refactor
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/controlconnection/challenge/challenge.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/controlconnection/connection_integration_test.go
  bctl/agent/controlconnection/connection_test.go
  bctl/agent/datachannel/datachannel.go
  bctl/daemon/daemon.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_integration_test.go
  bctl/daemon/servers/dataconnection/connection_test.go
  bctl/daemon/servers/dbserver/dbserver.go
  bctl/daemon/servers/kubeserver/kubeserver.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bctl/daemon/servers/webserver/webserver.go
  bctl/go.mod
  bzerolib/bzhttp/bzhttp.go
  bzerolib/channels/websocket/channel.go
  bzerolib/channels/websocket/signalr.go
  bzerolib/channels/websocket/websocket.go
  bzerolib/channels/websocket/websocketmessages.go
  bzerolib/connection/agentmessage/agentmessage.go
  bzerolib/connection/broker/broker.go
  bzerolib/connection/broker/mocks.go
  bzerolib/connection/connection.go
  bzerolib/connection/httpclient/httpclient.go
  bzerolib/connection/httpclient/httpclient_test.go
  bzerolib/connection/messenger/messenger.go
  bzerolib/connection/messenger/mocks.go
  bzerolib/connection/messenger/signalr/invocation.go
  bzerolib/connection/messenger/signalr/messages.go
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/messenger/signalr/signalr_test.go
  bzerolib/connection/transporter/mocks.go
  bzerolib/connection/transporter/transporter.go
  bzerolib/connection/transporter/websocket/mocks.go
  bzerolib/connection/transporter/websocket/websocket.go
  bzerolib/connection/transporter/websocket/websocket_test.go
  bzerolib/controllers/agentcontroller/agentcontroller.go
  bzerolib/controllers/agentcontroller/messages.go
  bzerolib/controllers/connectionnodecontroller/connectionnodecontroller.go
  bzerolib/controllers/connectionnodecontroller/messages.go
  bzerolib/controllers/spacescontroller/messages.go
  bzerolib/controllers/spacescontroller/spacescontroller.go
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/logger/logger.go
  bzerolib/tests/connectionnode/mockconnectionnode.go
  bzerolib/tests/mockserver.go
  bzerolib/tests/server/signalrserver.go
  bzerolib/tests/server/websocketserver.go
Labels: refactor

#123 Moving control channel to connection node
  .gitignore
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/agentidentity/agentidentity.go
  bctl/agent/controlchannel/agentidentity/messages.go
  bctl/agent/controlchannel/agentidentity/mocks.go
  bctl/agent/controlchannel/agentidentity/mocks/IAgentIdentityProvider.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/controlchannel/dataconnection/messages.go
  bctl/agent/controlconnection/challenge/challenge.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/controlconnection/connection_integration_test.go
  bctl/agent/controlconnection/connection_test.go
  bctl/agent/controlconnection/messages.go
  bctl/agent/datachannel/datachannel.go
  bctl/agent/keysplitting/mocks.go
  bctl/agent/plugin/db/actions/dial/dial.go
  bctl/agent/vault/vault.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_integration_test.go
  bctl/daemon/servers/dataconnection/connection_test.go
  bctl/daemon/servers/dataconnection/messages.go
  bctl/go.mod
  bzerolib/bzhttp/bzhttp.go
  bzerolib/connection/agentmessage/agentmessage.go
  bzerolib/connection/agentmessage/backendagentmessage.go
  bzerolib/connection/broker/broker.go
  bzerolib/keysplitting/bzcert/bzcertverifier.go
  bzerolib/messagesigner/messagesigner.go
  bzerolib/messagesigner/mocks.go
Labels: enhancement, Feature Branch

#148 Release 09/26
  .gitignore
  VERSION
  bctl/agent/agent.go
  bctl/agent/controlchannel/agentidentity/agentidentity.go
  bctl/agent/controlchannel/agentidentity/messages.go
  bctl/agent/controlchannel/agentidentity/mocks.go
  bctl/agent/controlchannel/agentidentity/mocks/IAgentIdentityProvider.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/controlchannel/dataconnection/messages.go
  bctl/agent/controlconnection/challenge/challenge.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/controlconnection/connection_integration_test.go
  bctl/agent/controlconnection/connection_test.go
  bctl/agent/controlconnection/messages.go
  bctl/agent/datachannel/datachannel.go
  bctl/agent/keysplitting/mocks.go
  bctl/agent/plugin/db/actions/dial/dial.go
  bctl/agent/vault/vault.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_integration_test.go
  bctl/daemon/servers/dataconnection/connection_test.go
  bctl/daemon/servers/dataconnection/messages.go
  bctl/go.mod
  bzerolib/bzhttp/bzhttp.go
  bzerolib/connection/agentmessage/agentmessage.go
  bzerolib/connection/agentmessage/backendagentmessage.go
  bzerolib/connection/broker/broker.go
  bzerolib/keysplitting/bzcert/bzcertverifier.go
  bzerolib/messagesigner/messagesigner.go
  bzerolib/messagesigner/mocks.go
Labels: release

#149 Fix integration test race
  VERSION
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlconnection/connection_integration_test.go
  bctl/daemon/servers/dataconnection/connection_integration_test.go
  bzerolib/tests/errors.go
Labels: bug, testing

#151 Fix dataconnection websocket send race condition
  VERSION
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/shellserver/shellserver.go
  bctl/daemon/servers/sshserver/sshserver.go
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/transporter/websocket/websocket.go
Labels: bug

#150 Fix/syn cert renewal
  VERSION
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/keysplitting/bzcert/bzcert.go
  bctl/daemon/keysplitting/keysplitting.go
  bctl/daemon/keysplitting/keysplitting_test.go
  bctl/go.mod
  bctl/go.sum
Labels: bug
