Repository bastionzero/bzero, pull requests merged in 2022-11, with the labels that each got.

#176 Cancellable Registration
  VERSION
  bctl/agent/config/client/systemd_test.go
  bctl/agent/main.go
  bctl/agent/registration/registration.go
Labels: refactor

#180 Fix Config Backwards Compatability
  VERSION
  bctl/agent/config/data/data.go
Labels: Hotfix

#182 Fix Config Backwards Compatibility in ShutdownState
  VERSION
  bctl/agent/config/data/data.go
Labels: bug, Hotfix

#181 Apply hotfix #180 and #182 on develop
  VERSION
  bctl/agent/config/data/data.go
Labels: bug

#179 SSH refurbish: Include non-RSA public keys when writing to known_hosts
  VERSION
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh.go
  bctl/agent/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/agent/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/plugin/ssh/actions/opaquessh/opaquessh_test.go
  bctl/daemon/plugin/ssh/actions/transparentssh/transparentssh_test.go
  bctl/daemon/servers/sshserver/sshserver.go
  bzerolib/bzio/fileio.go
  bzerolib/bzio/mocks.go
  bzerolib/plugin/ssh/knownhosts.go
Labels: bug

#177 Skip orgId claim check in bzcert verifier for personal orgs
  VERSION
  bzerolib/mrtap/bzcert/bzcertverifier.go
Labels: bug

#184 Fix switch logic in web websocket
  VERSION
  bctl/daemon/plugin/web/actions/webwebsocket/webwebsocket.go
Labels: Hotfix

#185 Hotfix: Fix switch logic in web websocket (#184)
  VERSION
  bctl/daemon/plugin/web/actions/webwebsocket/webwebsocket.go
Labels: Hotfix

#183 Service accounts [CWC-2056]
  .github/workflows/systemtest-ci-develop.yml
  .github/workflows/systemtest-ci-master.yml
  VERSION
  bctl/agent/agent.go
  bctl/agent/config/config.go
  bctl/agent/config/data/data.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/mrtap/mocks.go
  bctl/agent/mrtap/mrtap.go
  bctl/agent/registration/messages.go
  bctl/agent/registration/registration.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/mrtap/bzcert/bzcert.go
  bctl/daemon/mrtap/bzcert/mocks.go
  bzerolib/connection/agentmessage/agentmessage.go
  bzerolib/go.mod
  bzerolib/mrtap/bzcert/bzcert.go
  bzerolib/mrtap/bzcert/bzcertverifier.go
  bzerolib/mrtap/bzcert/bzcertverifier_test.go
  bzerolib/mrtap/bzcert/errors.go
  bzerolib/mrtap/bzcert/mocks.go
  bzerolib/mrtap/util/util.go
Labels: Feature Branch, ci-run-service-account-tests

#191 Release 11/28/22
  .github/workflows/systemtest-ci-develop.yml
  .github/workflows/systemtest-ci-master.yml
  VERSION
  bctl/agent/agent.go
  bctl/agent/config/config.go
  bctl/agent/config/data/data.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/controlchannelmessages.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/mrtap/mocks.go
  bctl/agent/mrtap/mrtap.go
  bctl/agent/registration/messages.go
  bctl/agent/registration/registration.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/exit/exit.go
  bctl/daemon/mrtap/bzcert/bzcert.go
  bctl/daemon/mrtap/bzcert/mocks.go
  bzerolib/connection/agentmessage/agentmessage.go
  bzerolib/go.mod
  bzerolib/mrtap/bzcert/bzcert.go
  bzerolib/mrtap/bzcert/bzcertverifier.go
  bzerolib/mrtap/bzcert/bzcertverifier_test.go
  bzerolib/mrtap/bzcert/errors.go
  bzerolib/mrtap/bzcert/mocks.go
  bzerolib/mrtap/util/util.go
Labels: release, ci-run-service-account-tests

#192 Apply codebuild role to assume for service account ci to develop
  .github/workflows/systemtest-ci-master.yml
  VERSION
Labels: bug, Hotfix
