Repository bastionzero/bzero, pull requests merged in 2023-03, with the labels that each got.

#218 Move and Use the Bastion Http Client
  VERSION
  bctl/agent/agent.go
  bctl/agent/agentreport/restartreport.go
  bctl/agent/bastion/agentidentity/agentidentity.go
  bctl/agent/bastion/agentidentity/messages.go
  bctl/agent/bastion/agentidentity/mocks/agentIdentityToken.go
  bctl/agent/bastion/bastion.go
  bctl/agent/bastion/messages.go
  bctl/agent/bastion/mocks/apiClient.go
  bctl/agent/bastion/report/logreport.go
  bctl/agent/controlchannel/agentidentity/mocks.go
  bctl/agent/controlchannel/agentidentity/mocks/IAgentIdentityProvider.go
  bctl/agent/controlchannel/controlchannel.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/connection_test.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/controlconnection/connection_integration_test.go
  bctl/agent/controlconnection/connection_test.go
  bctl/agent/datachannel/datachannel.go
  bctl/agent/plugin/db/actions/pwdb/certificate.go
  bctl/agent/plugin/db/actions/pwdb/client/bastion.go
  bctl/agent/plugin/db/actions/pwdb/pwdb.go
  bctl/agent/plugin/db/db.go
Labels: refactor

#226 Add documentation for build memory issue
  README.md
  VERSION
Labels: documentation

#227 Fix signalr deadlock when processing close messages
  VERSION
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/messenger/signalr/signalr_test.go
Labels: bug

#228 Upgrade to go1.20
  .gitignore
  Codebuild/unit-test.yml
  VERSION
  bctl/agent/go.mod
  bctl/daemon/go.mod
  bzerolib/go.mod
Labels: dependencies

#229 Use IdleTimeout in agent's dataconnection when daemon disconnects
  VERSION
  bctl/agent/controlchannel/dataconnection/connection.go
  bzerolib/connection/errors.go
Labels: enhancement

#230 SignalR: Send ping messages from client + handle server pings
  VERSION
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_test.go
  bzerolib/connection/messenger/messenger.go
  bzerolib/connection/messenger/mocks.go
  bzerolib/connection/messenger/signalr/errors.go
  bzerolib/connection/messenger/signalr/messages.go
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/messenger/signalr/signalr_test.go
Labels: bug
