Repository bastionzero/bzero, pull requests merged in 2023-02, with the labels that each got.

#206 Release 02-01-23
  VERSION
  bzerolib/unix/unixuser/unixuser_test.go
  bzerolib/unix/unixuser/useradd.go
Labels: release

#207 Set supplementary groups for shell users
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
Labels: bug

#208 Release 02-08-2023
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
Labels: release

#213 Fix agent graceful shutdown race
  VERSION
  bctl/agent/main.go
Labels: bug

#212 Send AgentType in GetActivationToken request during registration flow
  VERSION
  bctl/agent/agent.go
  bctl/agent/agenttype/messages.go
  bctl/agent/main.go
  bctl/agent/registration/messages.go
  bctl/agent/registration/registration.go
  start.sh
Labels: enhancement

#223 Use fixed certificate controller route
  VERSION
  bctl/agent/plugin/db/actions/pwdb/client/bastion.go
Labels: bug

#222 Fix pseudoterminal unit test
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
Labels: bug

#225 Release 02-27-2023 Part2
  VERSION
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal.go
Labels: release

#221 Fix signalr deadlock when processing close messages
  VERSION
  bzerolib/connection/messenger/signalr/signalr.go
  bzerolib/connection/messenger/signalr/signalr_test.go
Labels: bug
