Repository bastionzero/bzero, pull requests merged in 2023-05, with the labels that each got.

#237 Keycloak
  VERSION
  bzerolib/mrtap/bzcert/bzcertverifier.go
Labels: Feature Branch, ci-run-google, ci-run-keycloak

#239 Release 5-3-2023
  VERSION
  bctl/agent/main.go
  bctl/daemon/daemon.go
  bctl/daemon/go.mod
  bctl/daemon/go.sum
  bctl/daemon/mrtap/bzcert/bzcert.go
  bctl/daemon/mrtap/bzcert/zliconfig/zliconfig.go
  bctl/daemon/mrtap/bzcert/zliconfig/zliconfig_unix.go
  bctl/daemon/mrtap/bzcert/zliconfig/zliconfig_windows.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell_unix.go
  bctl/daemon/plugin/shell/actions/defaultshell/defaultshell_windows.go
  bctl/daemon/plugin/shell/shell.go
  bzerolib/mrtap/bzcert/bzcertverifier.go
  bzerolib/unix/unixuser/permissions.go
  bzerolib/unix/unixuser/unixuser.go
  bzerolib/unix/unixuser/unixuser_test.go
  bzerolib/unix/unixuser/useradd.go
Labels: release

#233 Windows Agent Registration [CWC-2481]
  VERSION
  bctl/agent/agent.go
  bctl/agent/agentservice_unix.go
  bctl/agent/agentservice_windows.go
  bctl/agent/constants_unix.go
  bctl/agent/constants_windows.go
  bctl/agent/errors.go
  bctl/agent/go.mod
  bctl/agent/go.sum
  bctl/agent/main.go
  bctl/agent/mocks/registration.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_unix.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_windows.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_unix.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_windows.go
  bzerolib/unix/unixuser/permissions_unix.go
  bzerolib/unix/unixuser/permissions_windows.go
  bzerolib/unix/unixuser/unixuser.go
  bzerolib/unix/unixuser/useradd.go
Labels: Feature Branch

#242 Release 05-17-23
  VERSION
  bctl/agent/agent.go
  bctl/agent/agentservice_unix.go
  bctl/agent/agentservice_windows.go
  bctl/agent/bastion/agentidentity/agentidentity.go
  bctl/agent/constants_unix.go
  bctl/agent/constants_windows.go
  bctl/agent/errors.go
  bctl/agent/go.mod
  bctl/agent/go.sum
  bctl/agent/main.go
  bctl/agent/mocks/registration.go
  bctl/agent/plugin/db/actions/pwdb/pwdb.go
  bctl/agent/plugin/db/actions/pwdb/pwdb_test.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_unix.go
  bctl/agent/plugin/shell/actions/defaultshell/pseudoterminal/pseudoterminal_windows.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_unix.go
  bctl/agent/plugin/ssh/authorizedkeys/authorizedkeys_windows.go
  bzerolib/unix/unixuser/permissions_unix.go
  bzerolib/unix/unixuser/permissions_windows.go
Labels: release

#243 Windows agent service re-resgitration [CWC-2625]
  VERSION
  bctl/agent/agentservice_windows.go
Labels: bug

#244 Enable cross-platform graceful shutdown of the daemon
  VERSION
  bctl/daemon/config.go
  bctl/daemon/daemon.go
  bctl/daemon/exit/exit.go
  bctl/daemon/servers/controlserver/controlserver.go
  bzerolib/bzos/errors.go
Labels: bug
