Repository bastionzero/bzero, pull requests merged in 2023-06, with the labels that each got.

#247 Ticker Memory Leak
  VERSION
  bzerolib/connection/messenger/signalr/signalr.go
Labels: bug

#252 Windows agent deployment
  .gitignore
  Codebuild/bzero-agent-release.yml
  VERSION
  release-scripts/create-manifest.sh
Labels: Feature Branch

#257 Kubectl fixes back to develop
  VERSION
  bctl/agent/plugin/kube/actions/exec/exec.go
  bctl/daemon/datachannel/datachannel.go
  bctl/daemon/plugin/kube/actions/exec/exec.go
  bzerolib/plugin/kube/utils/spdyconstants.go
Labels: Hotfix

#258 Inject agent version during build/release process
  Codebuild/bzero-agent-release.yml
  VERSION
Labels: bug

#253 Add credential delegation to AWS RDS postgreSQL connections (passwordless)
  VERSION
  bctl/agent/go.mod
  bctl/agent/go.sum
  bctl/agent/plugin/db/actions/pwdb/psql.go
  bctl/agent/plugin/db/actions/pwdb/pwdb.go
  bctl/agent/plugin/db/actions/pwdb/pwdb_test.go
  bctl/agent/plugin/db/actions/pwdb/sslproxy.go
Labels: Feature Branch
