Repository bastionzero/bzero, pull requests merged in 2023-01, with the labels that each got.

#201 Release 1-5-23
  .github/workflows/systemtest-ci-develop.yml
  .github/workflows/systemtest-ci-master.yml
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  DockerFile
  README.md
  VERSION
  bctl/agent/config/client/systemd.go
  bctl/agent/config/data/data.go
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlconnection/connection.go
  bctl/agent/registration/registration.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/go.mod
  bctl/go.sum
  bzerolib/connection/httpclient/httpclient.go
  bzerolib/connection/httpclient/httpclient_test.go
  bzerolib/go.mod
  bzerolib/go.sum
  bzerolib/mrtap/bzcert/bzcertverifier.go
  bzerolib/mrtap/bzcert/bzcertverifier_test.go
  bzerolib/mrtap/bzcert/errors.go
  bzerolib/mrtap/util/util.go
Labels: release

#202 Add new errors for when connection closes due to policy change
  VERSION
  bctl/daemon/exit/exit.go
  bctl/daemon/servers/dataconnection/connection.go
  bzerolib/connection/errors.go
Labels: bug

#203 Add support for different log levels
  VERSION
  bctl/agent/main.go
  bzerolib/logger/logger.go
Labels: bug

#198 Connection Idle Timeout
  VERSION
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/messages.go
  bctl/daemon/exit/exit.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_integration_test.go
  bzerolib/connection/errors.go
  bzerolib/tests/connectionnode/mockconnectionnode.go
Labels: enhancement

#204 Release 1-13-23
  VERSION
  bctl/agent/controlchannel/dataconnection/connection.go
  bctl/agent/controlchannel/dataconnection/connection_integration_test.go
  bctl/agent/controlchannel/dataconnection/messages.go
  bctl/agent/main.go
  bctl/daemon/exit/exit.go
  bctl/daemon/servers/dataconnection/connection.go
  bctl/daemon/servers/dataconnection/connection_integration_test.go
  bzerolib/connection/errors.go
  bzerolib/logger/logger.go
  bzerolib/tests/connectionnode/mockconnectionnode.go
Labels: release
